Repository GreyMatteOr/bangwords, pull requests merged in 2020-11, with the labels that each got.

#55 Feature/readme
  README.md
  src/assets/flowchart.png
  src/assets/hints.png
  src/assets/socket-path.png
  src/assets/wireframe.png
Labels: documentation

#58 Rooms
  src/App.js
  src/Gamepage/Gamepage.js
  src/Homepage/Homepage.js
  src/Lobby/Lobby.css
  src/Lobby/Lobby.js
  src/Lobby/Lobby.test.js
  src/WordSelector/WordSelector.js
Labels: 3, Function, Socket.IO, client, enhancement

#64 Feature/clear guess
  src/Gamepage/Gamepage.js
  src/Homepage/Homepage.js
  src/WordSelector/WordSelector.js
Labels: 3, Refactor, enhancement

#66 Testing2
  public/logo192.png
  public/logo512.png
  src/App.js
  src/Gamepage/Gamepage.js
  src/Gamepage/Gamepage.test.js
  src/Lobby/Lobby.test.js
  src/WordSelector/WordSelector.test.js
Labels: enhancement

#69 Feature/button design
  package-lock.json
  package.json
  src/App.js
  src/Gamepage/Gamepage.css
  src/Gamepage/Gamepage.js
  src/Homepage/Homepage.css
  src/Lobby/Lobby.css
  src/Lobby/Lobby.js
  src/WordSelector/WordSelector.css
  src/WordSelector/WordSelector.js
Labels: design, enhancement

#70 Leave room btn
  src/App.css
  src/App.js
  src/Gamepage/Gamepage.js
  src/Homepage/Homepage.css
  src/Lobby/Lobby.js
Labels: 3, Function, Socket.IO, client, design

#72 Chat
  src/App.js
  src/Chat/Chat.css
  src/Chat/Chat.js
  src/Chat/Chat.test.js
  src/Gamepage/Gamepage.js
  src/Lobby/Lobby.js
Labels: 3, Function, Socket.IO, client, enhancement

#76 Feature/app test
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/Gamepage/Gamepage.test.js
  src/Homepage/Homepage.js
  src/Lobby/Lobby.js
  src/WordSelector/WordSelector.js
Labels: Refactor, Testing

#77 Add chat.test.js
  src/Chat/Chat.js
  src/Chat/Chat.test.js
  src/Gamepage/Gamepage.test.js
Labels: enhancement

#79 Cleanup tests
  src/App.js
  src/Gamepage/Gamepage.test.js
Labels: Refactor, Testing

#81 Redesign gamepage
  public/index.html
  src/App.js
  src/Chat/Chat.js
  src/Chat/Chat.scss
  src/Gamepage/Gamepage.js
  src/Gamepage/Gamepage.scss
Labels: enhancement

#86 Footer
  src/App.js
  src/App.test.js
  src/Footer/Footer.js
  src/Footer/Footer.scss
  src/Footer/Footer.test.js
  src/Homepage/Homepage.js
Labels: enhancement

#83 Cleanup/css
  src/App.js
  src/App.scss
  src/App.test.js
  src/Gamepage/Gamepage.js
  src/Gamepage/Gamepage.scss
  src/Gamepage/Gamepage.test.js
  src/assets/lose.png
  src/assets/win.png
Labels: Cleanup, Refactor, design

#87 Feature/nav home onload
  src/App.js
  src/Chat/Chat.js
  src/Chat/Chat.scss
  src/Gamepage/Gamepage.js
  src/Gamepage/Gamepage.scss
  src/Homepage/Homepage.js
  src/Lobby/Lobby.js
  src/WordSelector/WordSelector.js
  src/WordSelector/WordSelector.scss
  src/assets/crown.png
  src/index.js
Labels: Cleanup, Refactor

#88 Player score
  src/App.js
  src/Chat/Chat.js
  src/Chat/Chat.scss
  src/Gamepage/Gamepage.js
  src/Gamepage/Gamepage.scss
  src/WordSelector/WordSelector.js
  src/WordSelector/WordSelector.scss
  src/assets/crown.png
Labels: 3, Cleanup, Refactor, Socket.IO, client, design, enhancement, server

#89 Readme finish
  README.md
  src/assets/gamepage.png
  src/assets/lobby.png
  src/assets/rename.png
  src/assets/winning.png
Labels: documentation
