Repository GreyMatteOr/bangwords, pull requests merged in 2020-10, with the labels that each got.

#17 Game class
  .babelrc
  package-lock.json
  package.json
  src/Game/Game.Test.js
  src/Game/Game.js
Labels: enhancement

#18 Feature/app layout
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/Gamepage/Gamepage.css
  src/Gamepage/Gamepage.js
  src/Homepage/Homepage.css
  src/Homepage/Homepage.js
  src/WordSelector/WordSelector.css
  src/WordSelector/WordSelector.js
  src/index.js
Labels: 1, enhancement

#25 Feature/fetch file
  src/APICalls/APICalls.js
  src/App.js
  src/Game/Game.Test.js
  src/Game/Game.js
  src/Homepage/Homepage.js
  src/WordSelector/WordSelector.js
Labels: 2, enhancement

#31 Feature/functionality
  src/APICalls/APICalls.js
  src/App.js
  src/Gamepage/Gamepage.css
  src/Gamepage/Gamepage.js
  src/History.js
  src/WordSelector/WordSelector.js
  src/index.js
Labels: 1, enhancement

#34 Chris tests
  src/Gamepage/Gamepage.js
  src/Gamepage/Gamepage.test.js
  src/WordSelector/WordSelector.js
  src/WordSelector/WordSelector.test.js
Labels: 2, Testing, enhancement

#37 Fix/api calls
  src/APICalls/APICalls.js
  src/App.js
  src/Homepage/Homepage.js
Labels: 2, bug

#38 Refactor Gamepage and WordSelector tests
  src/App.test.js
  src/Gamepage/Gamepage.test.js
  src/WordSelector/WordSelector.test.js
Labels: 1, enhancement

#39 Added baseline Socket client and configure environment.
  package-lock.json
  package.json
  src/App.js
Labels: 3, Socket.IO, client, enhancement

#41 Sockets
  src/APICalls/APICalls.js
  src/App.js
  src/Gamepage/Gamepage.js
  src/Homepage/Homepage.js
Labels: 3, Socket.IO, client, enhancement

#45 Design tweaks
  src/App.css
  src/App.js
  src/Gamepage/Gamepage.css
  src/Gamepage/Gamepage.js
  src/Homepage/Homepage.css
  src/Homepage/Homepage.js
  src/WordSelector/WordSelector.css
  src/WordSelector/WordSelector.js
Labels: 1, enhancement

#48 Feature/proptypes
  src/App.js
  src/Gamepage/Gamepage.js
  src/Homepage/Homepage.js
  src/WordSelector/WordSelector.js
Labels: Cleanup, documentation
